### ISSUE TITLE
Have error when build Project

### ISSUE THREAD

**Issue by hongnguyenx** [XopcT/ImageEditor#1]
Dear XopcT,
Really thanks for your project, it match some feature for edit image that I looking.
But I can't build source code download from Githup
Have error: 

"Error  5   The command ""Utilities\Bin\x86\fxc.exe" /T ps_2_0 /E main /Fo "C:\Users\hongnguyenx\Downloads\ImageEditor-master\ImageEditor-master\ImageEditor\Effects\Grayscale.ps" "C:\Users\hongnguyenx\Downloads\ImageEditor-master\ImageEditor-master\ImageEditor\Effects\Grayscale.fx"
"Utilities\Bin\x86\fxc.exe" /T ps_2_0 /E main /Fo "C:\Users\hongnguyenx\Downloads\ImageEditor-master\ImageEditor-master\ImageEditor\Effects\Negative.ps" "C:\Users\hongnguyenx\Downloads\ImageEditor-master\ImageEditor-master\ImageEditor\Effects\Negative.fx"
"Utilities\Bin\x86\fxc.exe" /T ps_2_0 /E main /Fo "C:\Users\hongnguyenx\Downloads\ImageEditor-master\ImageEditor-master\ImageEditor\Effects\BrightnessContrast.ps" "C:\Users\hongnguyenx\Downloads\ImageEditor-master\ImageEditor-master\ImageEditor\Effects\BrightnessContrast.fx"" exited with code 3.    ImageEditor"

Pls, U can help me check what problem here.!?
Thanks so much... !!!

**Comment by XopcT** [comment]
I've used shaders for some image effects. So you need to install DirectX SDK to be able to compile that shaders. The project will run after that.
