### ISSUE TITLE
Project doesn't compile VS 2017

### ISSUE THREAD

**Issue by jupagose** [XopcT/ImageEditor#2]
The command ""Utilities\Bin\x86\fxc.exe" /T ps_2_0 /E main /Fo "O:\C#Samples\ImageEditor-master\ImageEditor\Effects\Grayscale.ps" "O:\C#Samples\ImageEditor-master\ImageEditor\Effects\Grayscale.fx"
"Utilities\Bin\x86\fxc.exe" /T ps_2_0 /E main /Fo "O:\C#Samples\ImageEditor-master\ImageEditor\Effects\Negative.ps" "O:\C#Samples\ImageEditor-master\ImageEditor\Effects\Negative.fx"
"Utilities\Bin\x86\fxc.exe" /T ps_2_0 /E main /Fo "O:\C#Samples\ImageEditor-master\ImageEditor\Effects\BrightnessContrast.ps" "O:\C#Samples\ImageEditor-master\ImageEditor\Effects\BrightnessContrast.fx"" exited with code 3.	ImageEditor			

Where or how to get fxc.exe?

**Comment by XopcT** [comment]
Hello! Looks like you need to have DirectX SDK installed to compile those shaders

**Comment by jupagose** [comment]
OK im going to t@ke a look to it. Tks


Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by jupagose** [comment]
I Installed nuget Pdfium.windows it installs two files in main dir Pdfium_x86.dll and Pdfium_x64.dll, but PdfiumViewer doesn’t take care of it.

Finally I copied two folders (x86 and x64) from PdfViewer samples and now everything is working.


But have a question there is a way to force PdfViewer to work with Pdfium.windows

,


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
De: Vladimir Verbitsky <notifications@github.com>
Enviado: Thursday, July 12, 2018 2:27:33 AM
Para: XopcT/ImageEditor
Cc: jupagose; Author
Asunto: Re: [XopcT/ImageEditor] Project doesn't compile VS 2017 (#2)


Hello! Looks like you need to have DirectX SDK installed to compile those shaders

**Comment by XopcT** [comment]
Why do you need Pdfium to run the project?

**Comment by jupagose** [comment]
Sorry. I mixed some things here.

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by XopcT** [comment]
Ok :)
